# Generated by Django 4.2 on 2024-07-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sync_branch', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('repository_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'repository_branch',
            },
        ),
        migrations.CreateModel(
            name='BranchMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('role_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'branch_member',
            },
        ),
    ]
