# Generated by Django 4.2 on 2024-07-05 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository_group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, null=True)),
                ('group_id', models.IntegerField()),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
