# Generated by Django 4.2 on 2024-07-07 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository_group', '0002_branch_branchmember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repository_id', models.IntegerField()),
                ('branch_name', models.CharField(max_length=100)),
                ('hook_url', models.URLField()),
                ('remark', models.TextField(blank=True, null=True)),
                ('trigger_event', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
