# Generated by Django 4.2 on 2024-07-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository_group', '0003_hook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('authenticated', models.BooleanField(default=False)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
