# Generated by Django 4.2 on 2024-07-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repository_group', '0004_importedrepository'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='hook',
            table='branch_hook',
        ),
        migrations.AlterModelTable(
            name='importedrepository',
            table='import_repository',
        ),
    ]
