# Generated by Django 4.2 on 2024-07-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository_group', '0005_alter_hook_table_alter_importedrepository_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookTriggerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hook_url', models.URLField()),
                ('status', models.CharField(max_length=10)),
                ('trigger_time', models.DateTimeField(auto_now_add=True)),
                ('response_content', models.TextField()),
            ],
            options={
                'db_table': 'web_hook_trigger_record',
            },
        ),
    ]
